export const currentUser = {
  id: "1",
  name: "Alex Chen",
  email: "alex.chen@example.com",
  avatar: "",
  initials: "AC",
  level: 12,
  xp: 2840,
  xpToNext: 3500,
  streak: 7,
  points: 14250,
  joinedDate: "2025-09-15",
  coursesCompleted: 8,
  coursesInProgress: 3,
  totalHours: 156,
}

export const courses = [
  {
    id: "1",
    title: "Machine Learning Fundamentals",
    description: "Master the core concepts of ML including supervised and unsupervised learning, neural networks, and model evaluation.",
    category: "AI & Data Science",
    progress: 72,
    totalLessons: 24,
    completedLessons: 17,
    duration: "12 weeks",
    author: "Dr. Sarah Kim",
    authorAvatar: "",
    rating: 4.8,
    students: 3420,
    difficulty: "Intermediate",
    tags: ["Python", "TensorFlow", "Statistics"],
    image: "",
    deadline: "2026-03-15",
    materials: [
      { type: "video", title: "Introduction to ML", duration: "45 min" },
      { type: "reading", title: "Supervised Learning Deep Dive", duration: "30 min" },
      { type: "quiz", title: "ML Concepts Quiz", duration: "15 min" },
      { type: "project", title: "Build a Classifier", duration: "2 hours" },
    ],
  },
  {
    id: "2",
    title: "Advanced React Patterns",
    description: "Dive deep into advanced React patterns including compound components, render props, and state machines.",
    category: "Web Development",
    progress: 45,
    totalLessons: 18,
    completedLessons: 8,
    duration: "8 weeks",
    author: "Marcus Johnson",
    authorAvatar: "",
    rating: 4.9,
    students: 5100,
    difficulty: "Advanced",
    tags: ["React", "TypeScript", "Patterns"],
    image: "",
    deadline: "2026-04-01",
    materials: [
      { type: "video", title: "Component Composition", duration: "60 min" },
      { type: "reading", title: "State Management Patterns", duration: "25 min" },
      { type: "project", title: "Build a Component Library", duration: "3 hours" },
    ],
  },
  {
    id: "3",
    title: "UX Design Principles",
    description: "Learn the fundamentals of user experience design, from research methodologies to interaction design patterns.",
    category: "Design",
    progress: 90,
    totalLessons: 16,
    completedLessons: 14,
    duration: "6 weeks",
    author: "Elena Rodriguez",
    authorAvatar: "",
    rating: 4.7,
    students: 2800,
    difficulty: "Beginner",
    tags: ["Figma", "Research", "Prototyping"],
    image: "",
    deadline: "2026-02-28",
    materials: [
      { type: "video", title: "Design Thinking Process", duration: "50 min" },
      { type: "reading", title: "User Research Methods", duration: "35 min" },
      { type: "quiz", title: "UX Principles Quiz", duration: "20 min" },
    ],
  },
  {
    id: "4",
    title: "Cloud Architecture with AWS",
    description: "Build scalable, resilient cloud applications with AWS services including Lambda, DynamoDB, and ECS.",
    category: "Cloud Computing",
    progress: 30,
    totalLessons: 20,
    completedLessons: 6,
    duration: "10 weeks",
    author: "James Park",
    authorAvatar: "",
    rating: 4.6,
    students: 1950,
    difficulty: "Advanced",
    tags: ["AWS", "Serverless", "DevOps"],
    image: "",
    deadline: "2026-05-10",
    materials: [
      { type: "video", title: "AWS Fundamentals", duration: "55 min" },
      { type: "reading", title: "Serverless Architecture", duration: "40 min" },
      { type: "project", title: "Deploy a Microservice", duration: "4 hours" },
    ],
  },
  {
    id: "5",
    title: "Data Visualization with D3",
    description: "Create stunning interactive data visualizations using D3.js, from basic charts to complex network graphs.",
    category: "Data Science",
    progress: 15,
    totalLessons: 14,
    completedLessons: 2,
    duration: "7 weeks",
    author: "Aisha Patel",
    authorAvatar: "",
    rating: 4.5,
    students: 1600,
    difficulty: "Intermediate",
    tags: ["D3.js", "JavaScript", "SVG"],
    image: "",
    deadline: "2026-06-01",
    materials: [
      { type: "video", title: "D3.js Basics", duration: "40 min" },
      { type: "reading", title: "SVG and Canvas", duration: "30 min" },
    ],
  },
  {
    id: "6",
    title: "Product Management Essentials",
    description: "Learn how to take products from idea to launch, including roadmapping, prioritization, and stakeholder management.",
    category: "Business",
    progress: 100,
    totalLessons: 12,
    completedLessons: 12,
    duration: "5 weeks",
    author: "Tom Williams",
    authorAvatar: "",
    rating: 4.8,
    students: 4200,
    difficulty: "Beginner",
    tags: ["Strategy", "Agile", "Analytics"],
    image: "",
    deadline: "2026-01-20",
    materials: [
      { type: "video", title: "Product Discovery", duration: "50 min" },
      { type: "reading", title: "Prioritization Frameworks", duration: "25 min" },
      { type: "quiz", title: "PM Knowledge Check", duration: "15 min" },
    ],
  },
]

export const dailyTasks = [
  { id: "1", title: "Complete ML Quiz Chapter 5", course: "Machine Learning Fundamentals", type: "quiz", dueTime: "2 hours", priority: "high" },
  { id: "2", title: "Watch React Patterns Video", course: "Advanced React Patterns", type: "video", dueTime: "4 hours", priority: "medium" },
  { id: "3", title: "Review UX Case Study", course: "UX Design Principles", type: "reading", dueTime: "Tomorrow", priority: "low" },
  { id: "4", title: "Submit AWS Lab Assignment", course: "Cloud Architecture with AWS", type: "project", dueTime: "3 days", priority: "high" },
]

export const activityTimeline = [
  { id: "1", action: "Completed lesson", detail: "Neural Networks Basics", course: "Machine Learning Fundamentals", time: "2 hours ago", type: "complete" },
  { id: "2", action: "Earned achievement", detail: "7-Day Streak", course: "", time: "3 hours ago", type: "achievement" },
  { id: "3", action: "Started lesson", detail: "Compound Components", course: "Advanced React Patterns", time: "5 hours ago", type: "start" },
  { id: "4", action: "Scored 95%", detail: "UX Principles Quiz", course: "UX Design Principles", time: "Yesterday", type: "score" },
  { id: "5", action: "Completed project", detail: "Deploy a Microservice", course: "Cloud Architecture with AWS", time: "2 days ago", type: "complete" },
]

export const weeklyActivity = [
  { day: "Mon", hours: 2.5, tasks: 4 },
  { day: "Tue", hours: 1.8, tasks: 3 },
  { day: "Wed", hours: 3.2, tasks: 5 },
  { day: "Thu", hours: 2.0, tasks: 3 },
  { day: "Fri", hours: 4.1, tasks: 7 },
  { day: "Sat", hours: 1.5, tasks: 2 },
  { day: "Sun", hours: 2.8, tasks: 4 },
]

export const monthlyProgress = [
  { month: "Sep", completed: 3, started: 5 },
  { month: "Oct", completed: 5, started: 4 },
  { month: "Nov", completed: 8, started: 6 },
  { month: "Dec", completed: 12, started: 8 },
  { month: "Jan", completed: 15, started: 7 },
  { month: "Feb", completed: 18, started: 9 },
]

export const performanceData = [
  { subject: "Quizzes", score: 88 },
  { subject: "Projects", score: 92 },
  { subject: "Assignments", score: 85 },
  { subject: "Participation", score: 95 },
  { subject: "Exams", score: 78 },
]

export const achievements = [
  { id: "1", title: "Quick Learner", description: "Complete 5 lessons in one day", icon: "zap", unlocked: true, date: "2026-01-15" },
  { id: "2", title: "Streak Master", description: "Maintain a 7-day learning streak", icon: "flame", unlocked: true, date: "2026-02-10" },
  { id: "3", title: "Knowledge Seeker", description: "Enroll in 5 different courses", icon: "book-open", unlocked: true, date: "2025-12-20" },
  { id: "4", title: "Top Scorer", description: "Score 95% or above on any quiz", icon: "trophy", unlocked: true, date: "2026-02-01" },
  { id: "5", title: "Completionist", description: "Finish an entire course", icon: "check-circle", unlocked: true, date: "2026-01-20" },
  { id: "6", title: "Social Butterfly", description: "Help 10 students in discussions", icon: "users", unlocked: false, date: "" },
  { id: "7", title: "Night Owl", description: "Study for 2 hours after midnight", icon: "moon", unlocked: false, date: "" },
  { id: "8", title: "Marathon Runner", description: "Complete 100 total hours of learning", icon: "timer", unlocked: true, date: "2026-02-05" },
]

export const chatMessages = [
  { id: "1", role: "assistant" as const, content: "Hi Alex! I'm your AI learning assistant. I can help you with course materials, suggest study plans, and answer questions about your courses. What would you like help with today?" },
  { id: "2", role: "user" as const, content: "I'm struggling with the neural networks chapter in my ML course. Can you explain backpropagation simply?" },
  { id: "3", role: "assistant" as const, content: "Great question! Think of backpropagation like a feedback loop:\n\n1. **Forward Pass**: Your neural network makes a prediction\n2. **Calculate Error**: Compare the prediction to the actual answer\n3. **Backward Pass**: Go backwards through the network, figuring out how much each connection contributed to the error\n4. **Update Weights**: Adjust each connection to reduce the error\n\nIt's like a teacher grading a group project and telling each student exactly what they need to improve. The network keeps doing this until it gets better at making predictions.\n\nWould you like me to create a practice quiz on this topic?" },
]
