export const currentUser = {
  id: "1",
  name: "Alex Chen",
  email: "alex.chen@example.com",
  avatar: "",
  initials: "AC",
  level: 12,
  xp: 2840,
  xpToNext: 3500,
  streak: 7,
  points: 14250,
  joinedDate: "2025-09-15",
  coursesCompleted: 8,
  coursesInProgress: 3,
  totalHours: 156,
}

export const courses = [
  {
    id: "1",
    title: "Основы машинного обучения",
    description: "Master the core concepts of ML including supervised and unsupervised learning, neural networks, and model evaluation.",
    category: "AI & Data Science",
    progress: 72,
    totalLessons: 24,
    completedLessons: 17,
    duration: "12 недель",
    author: "Dr. Sarah Kim",
    authorAvatar: "",
    rating: 4.8,
    students: 3420,
    difficulty: "Intermediate",
    tags: ["Python", "TensorFlow", "Statistics"],
    image: "",
    deadline: "2026-03-15",
    materials: [
      { type: "video", title: "Introduction to ML", duration: "45 min" },
      { type: "reading", title: "Supervised Learning Deep Dive", duration: "30 min" },
      { type: "quiz", title: "ML Concepts Quiz", duration: "15 min" },
      { type: "project", title: "Build a Classifier", duration: "2 hours" },
    ],
  },
  {
    id: "2",
    title: "Принципы React",
    description: "Dive deep into advanced React patterns including compound components, render props, and state machines.",
    category: "Web Development",
    progress: 45,
    totalLessons: 18,
    completedLessons: 8,
    duration: "8 недель",
    author: "Marcus Johnson",
    authorAvatar: "",
    rating: 4.9,
    students: 5100,
    difficulty: "Advanced",
    tags: ["React", "TypeScript", "Patterns"],
    image: "",
    deadline: "2026-04-01",
    materials: [
      { type: "video", title: "Component Composition", duration: "60 min" },
      { type: "reading", title: "State Management Patterns", duration: "25 min" },
      { type: "project", title: "Build a Component Library", duration: "3 hours" },
    ],
  },
  {
    id: "3",
    title: "Принципы UX",
    description: "Learn the fundamentals of user experience design, from research methodologies to interaction design patterns.",
    category: "Design",
    progress: 90,
    totalLessons: 16,
    completedLessons: 14,
    duration: "6 недель",
    author: "Elena Rodriguez",
    authorAvatar: "",
    rating: 4.7,
    students: 2800,
    difficulty: "Beginner",
    tags: ["Figma", "Research", "Prototyping"],
    image: "",
    deadline: "2026-02-28",
    materials: [
      { type: "video", title: "Design Thinking Process", duration: "50 min" },
      { type: "reading", title: "User Research Methods", duration: "35 min" },
      { type: "quiz", title: "UX Principles Quiz", duration: "20 min" },
    ],
  },
  {
    id: "4",
    title: "Архитектура AWS",
    description: "Build scalable, resilient cloud applications with AWS services including Lambda, DynamoDB, and ECS.",
    category: "Cloud Computing",
    progress: 30,
    totalLessons: 20,
    completedLessons: 6,
    duration: "10 недель",
    author: "James Park",
    authorAvatar: "",
    rating: 4.6,
    students: 1950,
    difficulty: "Advanced",
    tags: ["AWS", "Serverless", "DevOps"],
    image: "",
    deadline: "2026-05-10",
    materials: [
      { type: "video", title: "AWS Fundamentals", duration: "55 min" },
      { type: "reading", title: "Serverless Architecture", duration: "40 min" },
      { type: "project", title: "Deploy a Microservice", duration: "4 hours" },
    ],
  },
  {
    id: "5",
    title: "Визуализация данных с помощью D3",
    description: "Create stunning interactive data visualizations using D3.js, from basic charts to complex network graphs.",
    category: "Data Science",
    progress: 15,
    totalLessons: 14,
    completedLessons: 2,
    duration: "7 недель",
    author: "Aisha Patel",
    authorAvatar: "",
    rating: 4.5,
    students: 1600,
    difficulty: "Intermediate",
    tags: ["D3.js", "JavaScript", "SVG"],
    image: "",
    deadline: "2026-06-01",
    materials: [
      { type: "video", title: "D3.js Basics", duration: "40 min" },
      { type: "reading", title: "SVG and Canvas", duration: "30 min" },
    ],
  },
  {
    id: "6",
    title: "Основы управления продуктом",
    description: "Learn how to take products from idea to launch, including roadmapping, prioritization, and stakeholder management.",
    category: "Business",
    progress: 100,
    totalLessons: 12,
    completedLessons: 12,
    duration: "5 недель",
    author: "Tom Williams",
    authorAvatar: "",
    rating: 4.8,
    students: 4200,
    difficulty: "Beginner",
    tags: ["Strategy", "Agile", "Analytics"],
    image: "",
    deadline: "2026-01-20",
    materials: [
      { type: "video", title: "Product Discovery", duration: "50 min" },
      { type: "reading", title: "Prioritization Frameworks", duration: "25 min" },
      { type: "quiz", title: "PM Knowledge Check", duration: "15 min" },
    ],
  },
]

export const dailyTasks = [
  { id: "1", title: "Выполнить тест по главе 5", course: "Основы машинного обучения", type: "quiz", dueTime: "2 часа", priority: "high" },
  { id: "2", title: "Посмотреть видео о принципах React", course: "Принципы React", type: "video", dueTime: "4 часа", priority: "medium" },
  { id: "3", title: "Просмотреть исследование UX", course: "Принципы UX", type: "reading", dueTime: "Завтра", priority: "low" },
  { id: "4", title: "Отправить лабораторную работу AWS", course: "Архитектура AWS", type: "project", dueTime: "3 дня", priority: "high" },
]

export const activityTimeline = [
  { id: "1", action: "Выполнен урок", detail: "Основы нейронных сетей", course: "Основы машинного обучения", time: "2 часа назад", type: "complete" },
  { id: "2", action: "Получено достижение", detail: "7-дневный подряд", course: "", time: "3 часа назад", type: "achievement" },
  { id: "3", action: "Начато занятие", detail: "Компоненты", course: "Принципы React", time: "5 часов назад", type: "start" },
  { id: "4", action: "Получено 95%", detail: "Тест по принципам UX", course: "UX Design Principles", time: "Вчера", type: "score" },
  { id: "5", action: "Выполнен проект", detail: "Deploy a Microservice", course: "Cloud Architecture with AWS", time: "2 дня назад", type: "complete" },
]

export const weeklyActivity = [
  { day: "Пн", hours: 2.5, tasks: 4 },
  { day: "Вт", hours: 1.8, tasks: 3 },
  { day: "Ср", hours: 3.2, tasks: 5 },
  { day: "Чт", hours: 2.0, tasks: 3 },
  { day: "Пт", hours: 4.1, tasks: 7 },
  { day: "Сб", hours: 1.5, tasks: 2 },
  { day: "Вс", hours: 2.8, tasks: 4 },
]

export const monthlyProgress = [
  { month: "Сен", completed: 3, started: 5 },
  { month: "Окт", completed: 5, started: 4 },
  { month: "Ноя", completed: 8, started: 6 },
  { month: "Дек", completed: 12, started: 8 },
  { month: "Янв", completed: 15, started: 7 },
  { month: "Фев", completed: 18, started: 9 },
]

export const performanceData = [
  { subject: "Тесты", score: 88 },
  { subject: "Проекты", score: 92 },
  { subject: "Задания", score: 85 },
  { subject: "Участие", score: 95 },
  { subject: "Экзамены", score: 78 },
]

export const achievements = [
  { id: "1", title: "Быстрый ученик", description: "Выполните 5 уроков в один день", icon: "zap", unlocked: true, date: "2026-01-15" },
  { id: "2", title: "Мастер подряд", description: "Поддерживайте 7-дневную учебную серию", icon: "flame", unlocked: true, date: "2026-02-10" },
  { id: "3", title: "Поиск знаний", description: "Запишитесь на 5 разных курсов", icon: "book-open", unlocked: true, date: "2025-12-20" },
  { id: "4", title: "Топ-оценщик", description: "Получите 95% или выше на любом тесте", icon: "trophy", unlocked: true, date: "2026-02-01" },
  { id: "5", title: "Завершающий", description: "Завершите весь курс", icon: "check-circle", unlocked: true, date: "2026-01-20" },
  { id: "6", title: "Социальный бабочка", description: "Помогите 10 студентам в обсуждениях", icon: "users", unlocked: false, date: "" },
  { id: "7", title: "Ночная сова", description: "Учеба 2 часа после полуночи", icon: "moon", unlocked: false, date: "" },
  { id: "8", title: "Марафон", description: "Выполните 100 часов обучения", icon: "timer", unlocked: true, date: "2026-02-05" },
]

export const chatMessages = [
  { id: "1", role: "assistant" as const, content: "Привет! Я ваш ассистент по обучению. Я могу помочь вам с материалами курса, предложить учебные планы и ответить на вопросы о ваших курсах. Что бы вы хотели помочь сегодня?" },
]
